### ISSUE TITLE
Feature request: preview elm-doc document comment locally

### ISSUE THREAD

**Issue by uehaj** [elm-lang/elm-lang.org#169]
Current Elm-tool chain lacks the way to preview [document comment](http://library.elm-lang.org/Documentation.html) of elm source, locally and quickly.

You can extract information from Elm source to a json file by elm-doc command, but to view it, you have to publish the Elm project includes the newest json to github and change and run [catalogs in elm-get](https://github.com/elm-lang/elm-get/blob/master/website/content/src/Catalog.elm) as an Elm program in some way. If you want to check document before release, it is inconvenient.

I wish we could preview document in easy and quick way, and locally (before push to github).

**Comment by vilterp** [comment]
Agreed; a way to generate the HTML locally would be useful.

**Comment by evancz** [comment]
It should be easier with how things work on package.elm-lang.org now. All the pages are .elm files that bring in some JSON ([like this one](https://github.com/elm-lang/package.elm-lang.org/blob/master/frontend/Page/Package.elm)), so I think it's plausible to break that out into a thing that generates HTML for anyone. Perhaps package.elm-lang.org could just be a consumer of that tool rather than owning it?

**Comment by evancz** [comment]
I added this project to this list https://github.com/elm-lang/projects so that someone can potentially get to it before me!

**Comment by uehaj** [comment]
Thanks!

**Comment by evancz** [comment]
I'm gonna close this issue because this repo will never resolve it. I think it's possible to generate docs with the existing elm-doc tool. It will spit out everything as JSON, so someone can create a little tool that formats that into an HTML page. I think that is a plausible way to go.
