### ISSUE TITLE
bogus hit/link in library catalog

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#173]
On http://library.elm-lang.org/catalog/elm-lang-Elm/0.13, entering `fmod` into the search box, leads to a page claiming that function `fmod` exists in module `Color`, along with a link http://library.elm-lang.org/catalog/elm-lang-Elm/0.13/Color#fmod, but that link anchor does not exist on that page (and indeed the `Color` module does not export `fmod`).

**Comment by jvoigtlaender** [comment]
Just a notice that this problem still exists. Entering `fmod` into the search box on http://package.elm-lang.org/packages/elm-lang/core/1.1.0 leads to a page claiming that function `fmod` exists in module `Color`, along with a link http://package.elm-lang.org/packages/elm-lang/core/1.1.0/Color#fmod, even though the latter is not valid.

**Comment by evancz** [comment]
I recall fixing things up such that only publicly exported things make it to the docs, so I think what this means is that `fmod` is actually in the public API but not in the docs. The fix may be to go through and be stricter with module exports in core.

**Comment by jvoigtlaender** [comment]
Right, checking I now see that the `Color` module has no explicit export list.

So, would the idea be that the `core` modules should only export those functions that are contained in the documentation?

(A more general idea might be that `elm-package` should warn, or even error out, prior to uploading a package, when a function in the public API of a package is not in the docs.)

**Comment by evancz** [comment]
I think https://github.com/elm-lang/elm-compiler/issues/841 sort of covers that, but it definitely does not hook into `elm-package`. Perhaps we can consolidate all of these issues on the elm-package repo under "Give warnings/errors when @docs do not match exports"?

**Comment by jvoigtlaender** [comment]
Yes, having `elm-doc` warn about missing documentation like in https://github.com/elm-lang/elm-compiler/issues/841 would be a very good start. I must admit that I never ran `elm-doc` locally. I just used `elm-package` and then relied on the documentation rendering on the catalog pages. So I would have missed those warnings. But if `elm-package` or its user guide tells users that they should first run `elm-doc` locally and check the output, that would be fine.

About the specific situation with `core`: Is the intention there that exactly those functions and types are part of the public API for which you have written documentation? If so, it would not be too complicated for someone to go through the modules and add explicit export lists to that effect. But it only makes sense if you declare that this is the intention.

**Comment by evancz** [comment]
Ideally with `elm-doc` it'd spit stuff out in machine readable form, such that it's easy to surface the errors when calling `elm-package`.

With `core`, that is definitely the intention. There have been cases where stuff was missing from the public docs in the past, so I can't give a 100% guarantee that everything lives up to that intention. The one exception I can think of is `Text.markdown` which is for internal use only. We're bumping to 2.0.0 soon, so it may be a good time to take that out and have it just appear in `Native.Text`.

I think the policy can be one file means one PR, [follow this format](https://github.com/elm-lang/core/blob/master/src/Dict.elm#L1-L11), be relatively aggressive because we'll see it all with `elm-package diff`, and bring up anything that looks odd in the PR and we can figure it out.

**Comment by jvoigtlaender** [comment]
Through with all files. :-)

**Comment by evancz** [comment]
Haha, thank you so much for doing this! :D

This is catching quite a few oddities as well. You rock!

**Comment by evancz** [comment]
I also love that all the PRs are listed here alphabetically, slowly turning purple as I work through them :) :+1:

**Comment by evancz** [comment]
Let's track further improvements at https://github.com/elm-lang/elm-compiler/issues/933
