### ISSUE TITLE
Marked issue with 0.12 Blog post

### ISSUE THREAD

**Issue by giodamelio** [elm-lang/elm-lang.org#209]
Somthing is wrong with http://elm-lang.org/blog/announce/0.12.elm. It is probably https://github.com/elm-lang/elm-lang.org/blob/master/frontend/public/blog/announce/0.12.elm#L206, but I don't have the environment set up to test the site. Not sure why marked can't highlight json though.

**Comment by thSoft** [comment]
http://elm-lang.org:1234/blog/announce/0.12 throws a runtime error. Is this the same issue?

**Comment by jvoigtlaender** [comment]
The answer to why `marked` can't highlight json (here), is that https://github.com/elm-lang/elm-lang.org/blob/master/resources/highlight/highlight.pack.js, which is used for highlighting, is currently a version with built-in support for only `bash`, `haskell`, `elm`, `javascript`. It would be easy to replace it by a version additionally supporting `json`. If that would fix this issue here, great.

**Comment by jvoigtlaender** [comment]
There are also other blog posts with erroneous behavior, e.g., http://elm-lang.org/blog/announce/0.12.3.

**Comment by jvoigtlaender** [comment]
As a heads up: The `marked`/`highlight` stuff has been updated to support `json` a while ago, so that was not the issue here. The pages are still erroring, with messages as shown [here](https://github.com/elm-lang/elm-lang.org/issues/431).

**Comment by jvoigtlaender** [comment]
The causes are [this block](https://github.com/elm-lang/elm-lang.org/blob/e52cbbb93ceff39947abbb8c5c70823cd60521ef/src/pages/blog/announce/0.12.elm#L39-L41) and [this block](https://github.com/elm-lang/elm-lang.org/blob/e52cbbb93ceff39947abbb8c5c70823cd60521ef/src/pages/blog/announce/0.12.3.elm#L74-L76).

**Comment by jvoigtlaender** [comment]
This issue can be closed. The subject matter and cause are covered by the more comprehensive issue https://github.com/elm-lang/elm-lang.org/issues/450.
