### ISSUE TITLE
Set up instructions in README.md were not right for me

### ISSUE THREAD

**Issue by raould** [elm-lang/elm-lang.org#279]
Ubuntu 14.04 LTS / x86.
1) i had to run "cabal configure" again after "cabal install --only-dependencies" -- at least the thing told me to do that which is nice, but it feels bad that it doesn't match the instructions. is this out of date across all system types or just mine?
2) when i finally run-elm-website it spews out "you may need to install it with: elm-get install johnpmayer/elm-webgl 0.1" like 6 or 7 times. and the kicker is when i do that command, i'm told "elm-get: command not found" :-(

**Comment by raould** [comment]
So I also think the mish-mash of all the different ways to get elm tools is not very unified and clear and easy and helpful for newbies.

e.g. i tried "elm-package install elm-get" and that didn't work

so then i tried this and got a real WTF?!
$ cabal install elm-get
Resolving dependencies...
In order, the following would be installed:
publicsuffixlist-0.1 (new package)
http-client-0.3.8.2 (new version)
http-client-tls-0.2.2 (reinstall) changes: http-client-0.4.11.2 -> 0.3.8.2
elm-get-0.1.3 (new package)
cabal: The following packages are likely to be broken by the reinstalls:
elm-package-0.5
Use --force-reinstalls if you want to install anyway.

**Comment by evancz** [comment]
It sounds like your configuration is really freaky. It sounds like you might be in [this scenario](http://www.reddit.com/r/elm/comments/34np4m/how_to_uninstall_elm/).

Are you new to using Haskell? Are you using cabal sandboxes when you run `cabal install`? If that question makes no sense, that's totally fine. `cabal` things are pretty crazy.

The best route will probably be to [run this fubar.sh script](http://www.reddit.com/r/elm/comments/34np4m/how_to_uninstall_elm/cqwe2qw) that'll clear *all* cabal packages on your system. It looks like you have a lot of conflicting packages. This is called "cabal hell" and it was a pretty bad problem in Haskell recently because cabal defaulted to global installs for everything. This meant different projects needed to sync up which was bad. "cabal sandboxes" are meant to keep all the dependencies separate. One thing to keep in mind is that even if you run `cabal install cabal-install` the actually binary on your PATH may not be the new version. I have been bitten by that before.

Finally, I updated the readme for 0.15 so I'm going to close this for now hoping that things are better. If things mess up again, can you post the transcript of what happened on the command line? What exact commands did you run? What version of cabal do you have? What version of GHC are you using? How did you install that? etc.
