### ISSUE TITLE
npm install doesn't support 32bit/x86 Ubuntu 14.04

### ISSUE THREAD

**Issue by raould** [elm-lang/elm-lang.org#315]
Please update the install instructions to be more clearly explicit about what machine types are supported. That would (have) save(d) people (like, say, me :-) a lot of wasted time and frustration.

**Comment by dagoof** [comment]
voting for this issue; although I'd just prefer to have support for x86

**Comment by jvoigtlaender** [comment]
Concerning `npm`, the install instructions point to https://www.npmjs.com/package/elm. So that is the place where it should be noted which machines are supported. The way to get something noted there is to change the `README.md` at https://github.com/kevva/elm-bin. So open an issue for this at https://github.com/kevva/elm-bin/issues? (Also the desire to add more supported machine types is an issue for there, not here.)
