### ISSUE TITLE
elm-lang.org is down

### ISSUE THREAD

**Issue by michaelsbradleyjr** [elm-lang/elm-lang.org#406]
The site's down and it has been since at least 15:51 GMT on 21 Oct 2015.

I realize the site being down doesn't really touch on the source code in this repo, but I wasn't sure if there was a better way to give a heads up to the folks responsible for it. A few people have tweeted @evancz regarding the same.

If it *seems* like it's still up when you load it in your browser, do a refresh and/or check:

http://downforeveryoneorjustme.com/elm-lang.org

**Comment by michaelsbradleyjr** [comment]
Would it be possible to have the strictly static content hosted via GitHub pages, which practically "never" goes down? I understand that the *try* page needs a live back-end.

**Comment by jvoigtlaender** [comment]
There *is* not much "strictly static" content there (in the sense of HTML pages). Even the blog pages etc. are Elm code that is rendered (as JavaScript which creates DOM elements) when you request a page. See, e.g., https://github.com/elm-lang/elm-lang.org/blob/master/src/pages/blog/blazing-fast-html.elm. That is the Elm file which is responsible for the page http://elm-lang.org/blog/blazing-fast-html. While to you that page might look like a static page that could be hosted on GitHub, it is not really. As the Elm file I link to shows. (Of course, some tricks could be played at deployment, like actually rendering the DOM, then doing some kind of scraping, capturing the DOM as HTML and then host *that* HTML on GitHub. But overall, it's a more complicated story than just "move stuff over to GitHub, so that there will be no reachability problems anymore".)

**Comment by seliopou** [comment]
Those are static pages. After compilation, there is no server-side computation that needs to be performed in order to serve the content. You just serve the generated JavaScript and HTML files, which will then run in the browser and create the intended interface. This likely true of all the blog posts and documentation. They could easily be hosted on GitHub pages, Amazon S3, or whatnot, with a CDN in front of them.

**Comment by michaelsbradleyjr** [comment]
Yes, I was assuming that the `.elm` pages, posts, etc. got compiled once and then served either from an in-mem cache or from disk. I'll be honest and say that I didn't really look at the Haskell code for the server part of the website. I have done so just now, and I see that there is logic to compile and serve up pages, but my *guess* is that the actual compilation only happens once per page.

**Comment by jvoigtlaender** [comment]
@seliopou, I know that is the case in principle. :smile:

I was more trying to talk about the practicalities of deployment. Sure it's possible to arrange things in a "more static / CDN friendly way". But it needs work, was all I was trying to say. Maybe I didn't do so well. (Also, I haven't looked into the server code myself, but whar @michaelsbradleyjr says makes sense.)

**Comment by evancz** [comment]
My hosting service (Digital Ocean) had some maintenance scheduled for some time in a 5+ hour range, so I just had to restart things.

Sorry for the issues here!

**Comment by ynimous** [comment]
FYI: elm-lang.org seems to be down currently.

**Comment by michaelsbradleyjr** [comment]
Confirmed: http://downforeveryoneorjustme.com/http://elm-lang.org/

**Comment by jmelfi** [comment]
@evancz any news on when this will be back up?

**Comment by michaelsbradleyjr** [comment]
@jmelfi I don't think it's been down continuously since Nov 22. But it definitely is down again at the time of this comment.

**Comment by ostronom** [comment]
Down again.

**Comment by jmelfi** [comment]
#437 is a copy of this notification.  Love this language so far!

**Comment by aestheticsdata** [comment]
down again

**Comment by romatthe** [comment]
Seems to be down again...

**Comment by jmelfi** [comment]
appears up now at least

**Comment by gisborne** [comment]
Down.

**Comment by gisborne** [comment]
Been down for a few days. I was just wanting to start getting into Elm for a major project, but this really gives me pause.

**Comment by jmelfi** [comment]
I didn't see this a few days ago.  I can resolve it now.  Are you still unable to resolve?

**Comment by gisborne** [comment]
I was trying to load this page:
http://elm-lang.org/guide/reactivity#signals

The main page is up, but that one still fails.

**Comment by jvoigtlaender** [comment]
That page does not exist any more. Simple as that. All the `/guide/...` pages do not exist anymore. See https://github.com/elm-lang/elm-lang.org/pull/567.

**Comment by jmelfi** [comment]
@gisborne it appears the guide is located here: http://guide.elm-lang.org/ as a gitbook now.

**Comment by justuseapen** [comment]
It's down rn
