### ISSUE TITLE
No mention of Haskell?

### ISSUE THREAD

**Issue by taoeffect** [elm-lang/elm-lang.org#408]
Elm seems very Haskell inspired, but I can't find the word "Haskell" anywhere in any of the obvious places on the website. That makes me sad. I was hoping for a few words about the connection.

**Comment by jvoigtlaender** [comment]
How familiar are you with other functional languages? For example, various ML dialects?

Maybe when you say "Haskell inspired", that's because you know Haskell. I'm just wondering whether you may be biased, and actually someone else with familiarity with OCaml would claim that Elm is more "OCaml inspired".

Elm is definitely "functional programming inspired", and "functional programming" appears all over the place on the website.

**Comment by evancz** [comment]
The website is tailored for the bulk of users coming to learn Elm. If someone has no familiarity with OCaml, using at a reference point is not so helpful. So let's translate your concern to other languages:

  * "Haskell seems very inspired by Miranda, but I can't find that anywhere on the website."
  * "OCaml seems very inspired by SML, but ..."
  * "F# seems very inspired by OCaml and SML, but ..."
  * "C# seems very inspired by Java, but ..."

The point of the website is not to document the entire intellectual history of the language, but to help people learn it quickly. If the OCaml website was full of links to SML and Haskell, it would be super confusing. Same as if the Python website was full of links to Ruby. Yes, things are related and that is important, but I'm not running an ad campaign for other languages, same as Haskell is not running an ad campaign for Elm.

**Comment by evancz** [comment]
To clarify the connection more though, I'd say Elm is an ML with *syntax* like Haskell. If you compare semantics, Elm is way closer to OCaml and SML. These are the kinds of details that I think would actively discourage JS folks when they come across their first type functional language. It shouldn't be a research project involving 3 other languages just to figure out what Elm even is.

**Comment by taoeffect** [comment]
Thanks for the responses.

I'm curious, @evancz, which has had a greater influence on Elm, Haskell or OCaml, or are they about the same?

Also, I'm noticing a lot of mentions of OCaml, but the Elm compiler itself is written in Haskell. If OCaml was the chief inspiration, then why write Elm in Haskell instead of OCaml?

**Comment by thomasb892** [comment]
Btw, seems like a Haskell fanboy forcefully wants to deliver credit to Haskell. Well that's unfair!, I know Haskell is/was underrated that also for good reason but that does not mean wherever you find a functional language tell them to praise Haskell, in fact Haskell was not the first functional language to be invented. Let the compiler be written in Haskell, parsers are easier to implement in Haskell, so do you want to say "since Elm's compiler is written in Haskell, it is inspired by Haskell". .NET runtime was written in C but was it inspired by C? I guess even you would says its inspired by Java. They used C because they found some advantage and/or just felt like using it

**Comment by shadowdoom3553** [comment]
Agreed, I never thought that haskell fanboys would come to this extent to give inspirational credit of elm to Haskell. The author clearly state that it is insipired my ML and this is forceful nitpicking to promote Haskell. @taoeffect is biased.

**Comment by taoeffect** [comment]
Where is all of this bizarre nonsense spam coming from all of a sudden?

**Comment by evancz** [comment]
I want to keep issues for tracking bugs. If folks want to discuss things, it's best to do that in community forums like Slack or Discourse.

About why this revived, this is something that happens on closed issues, especially when people feel very strongly in one way or the other. It is one of the realities of using GitHub. Is it for work? Is it for questions? Is it for discussions? The design makes it so everyone decides for themselves. Daily event at a certain point :P
