### ISSUE TITLE
Runtime Error: Cannot use 'in' operator to search for 'ctor' in null

### ISSUE THREAD

**Issue by pdamoc** [elm-lang/elm-lang.org#438]
```elm
import Html exposing (..) 

t = div [] [text "hello"]

main = text <| toString t
```

**Comment by pdamoc** [comment]
I don't know if it is useful but using `show` also throws the same error:

```elm
import Html exposing (..) 
import Graphics.Element exposing (show) 

t = div [] [text "hello"]

main = show t
```

**Comment by mrandri19** [comment]
same error when I tried to:
```
model : Model
model = {
    currentView = homeView,
    counter = 0
    }

p [] [ text (toString model) ]
```

**Comment by jvoigtlaender** [comment]
This is actually an error that does not quite make sense to be tracked here, in the `elm-lang.org` repo. It belongs in the `core` repo, and is indeed tracked there: https://github.com/elm-lang/core/issues/488 (and has a potential fix PR: https://github.com/elm-lang/core/pull/183).

@pdamoc, can you close the issue here?

**Comment by pdamoc** [comment]
I have no recollection as to  why I posted this error here. It might have made sense back in December but it does not make sense now. 

Thank you for your kindness Janis!
