### ISSUE TITLE
Cabal hell cost you a contributor :(

### ISSUE THREAD

**Issue by jessep** [elm-lang/elm-lang.org#439]
I had the intention of making your examples look better by adding a css framework to the page, and I've given up. I got into cabal hell trying to get the site running and do not feel like spending any more hours on it. I'm just a curious programmer, haven't used Haskell before, and have no idea how deep this rabbit hole can go.

Anyway, just wanted to give you that feedback. Is it possible that using Stack instead of Cabal could make it easier to get new people onboard?

**Comment by jvoigtlaender** [comment]
> I got into cabal hell trying to get the site running and do not feel like spending any more hours on it. I'm just a curious programmer, haven't used Haskell before, and have no idea how deep this rabbit hole can go.

If you were just to give us a tiny bit more feedback (like: what did actually happen), that would be nice.

Also, it is not impossible that if you had told us what the problem is, after one hour of trying (instead of trying for many hours on your own), maybe we could have told you the one thing you were doing wrong and which, if done correctly, would have gotten you over whatever hurdle you were facing.

**Comment by jessep** [comment]
Haha, good point! I don't know why I didn't post the issue in the first place. Okay, here's the error:

```
(workflowy)jessep:elm-lang.org jessep$ cabal install --only-dependencies
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: elm-website-0.1.0.2 (user goal)
trying: snap-core-0.9.8.0 (dependency of elm-website-0.1.0.2)
trying: vector-0.11.0.0/installed-b1f... (dependency of snap-core-0.9.8.0)
next goal: elm-package (dependency of elm-website-0.1.0.2)
rejecting: elm-package-0.5, 0.4, 0.2.2, 0.2.1, 0.2 (conflict:
vector==0.11.0.0/installed-b1f..., elm-package => vector>=0.10 && <0.11)
Dependency tree exhaustively searched.
```

**Comment by jvoigtlaender** [comment]
So apparently you didn't follow the instructions starting at https://github.com/elm-lang/elm-platform/blob/master/README.md#get-haskell-working *at all*?

You wouldn't issue any call like `cabal install --only-dependencies` on your own if you were following those instructions.

The README of https://github.com/elm-lang/elm-lang.org tells you you *should* follow those instructions.

Hmm, do you see the problem? There are instructions how to do the right thing. You ignore them. Then wonder why stuff is not working.

**Comment by jvoigtlaender** [comment]
I was overstating the case of "not running `cabal install --only-dependencies`" on your own. You will do so for building the website itself, of course. But not for the prior "First get the Elm developer workflow setup by reading the build from source instructions, then running this script ..." stuff. I'm questioning whether you did all that previous stuff correctly. Maybe you can show your full shell session?

**Comment by jessep** [comment]
Hrm, maybe I started this with a bad tone, but yours isn't super friendly right now. Regardless, I'll submit a pull request pulling this into bullets to help other skimmers like myself who are just looking for the instructions, avoid the issue of not reading the instructions embedded in the text.

**Comment by jessep** [comment]
Also, I see your second comment is friendlier :)

**Comment by jvoigtlaender** [comment]
Yeah, sorry about the first post. I guess it was my "waking up Saturday morning to a complaint without useful information" reaction. :smile:

Unfortunately, I'll be out of contact for most of the weekend. But I can try to look into what exactly happened concerning the package constraint here, on Monday.

**Comment by jessep** [comment]
No worries. I'm going through the instructions now, hopefully they will work.

**Comment by jessep** [comment]
Alrighty, I have now followed all of the instructions and it worked until the last step. Didn't look much into the current error because I haven't had time, will dig eventually, but looks the URL in question is returning null

```
(workflowy)jessep:elm-lang.org jessep$ ./dist/build/run-elm-website/run-elm-website
Setting up examples . problem compiling src/editor/EditorControls.elm

failure when running: elm-make --yes src/editor/EditorControls.elm --output=gen/editor/controls.js
failed with 'FailedConnectionException2 "package.elm-lang.org" 80 False getAddrInfo: does not exist (nodename nor servname provided, or not known)' when sending request to
    <http://package.elm-lang.org/all-packages?elm-package-version=0.5.1&since=2015-12-05%2007%3A13%3A44.92023%20UTC>
```

**Comment by jvoigtlaender** [comment]
Well, at least it's not "Cabal hell" anymore. :smile:

And I know what the problem is: the space (character `%20`) in the time stamp. Indeed the link

http://package.elm-lang.org/all-packages?elm-package-version=0.5.1&since=2015-12-05%2007%3A13%3A44.92023%20UTC

is returning "null", but the link

http://package.elm-lang.org/all-packages?elm-package-version=0.5.1&since=2015-12-05%2107%3A13%3A44.92023%20UTC

is returning the proper result.

The fault is in [this line](https://github.com/elm-lang/elm-package/blob/7a614594183471530bf415b03b0f57d6f959f322/src/Catalog.hs#L66) in the `elm-package` repository. The `show time` call there creates spaces, which lead to the above situation.

I'll open an issue over there.

**Comment by jvoigtlaender** [comment]
Actually, it's not the space per se. It's that [this test](https://github.com/elm-lang/package.elm-lang.org/blob/1b7cde09f79f6ff93d34eaef47f36f1efeff55ba/src/backend/Routes.hs#L316) came out as `False` in your case. It would have come out `True` if either:
* the time stamp would have been sufficiently old (for example, replace `2015` by `2014` in the above URL)
* the `elm-package-version` would have been `0.16` instead of `0.5.1` (again easily testable by changing the above URL a bit).

Which begs the question: Why is it `0.5.1` in your case?

Can you show more of your shell session? The instructions from https://github.com/elm-lang/elm-platform, with call `runhaskell BuildFromSource.hs 0.16`, shouldn't have given you that old version of `elm-package`.

**Comment by jvoigtlaender** [comment]
... same with call `runhaskell BuildFromSource.hs master`. Shouldn't have given you version `0.5.1` of `elm-package` either.

**Comment by jvoigtlaender** [comment]
@jessep, can this issue be closed?

**Comment by jessep** [comment]
Hi, yep! Sorry, you helped me figure it out. I had installed the wrong version. I need to get better at following instructions precisely :)
