### ISSUE TITLE
KeyPresses example broken in Firefox

### ISSUE THREAD

**Issue by frankschmitt** [elm-lang/elm-lang.org#440]
# Summary
The keypresses example (http://elm-lang.org/examples/key-presses ) seems to be broken in Firefox - the default text "The last key you pressed was: '\\0'" never changes when pressing a key.

It works in Safari and Chrome, though. 

# System info
- OS: OS X 10.10.5
- Firefox version 42.0
- Chrome version 47.0.2526.73 (64-bit)
- Safari version 8.0.8 (10600.8.9)

**Comment by jvoigtlaender** [comment]
@evancz, do you see what I meant over in https://github.com/elm-lang/core/pull/435#issuecomment-162339620? I don't know how many of these issues about the very same thing I have dealt with, or answered on the mailing list, in the last few weeks. Too many. It could be fixed with a `core` patch release.

@frankschmitt, see what I wrote in https://github.com/elm-lang/elm-platform/issues/123#issuecomment-162338027.

**Comment by frankschmitt** [comment]
@jvoigtlaender Sorry, I didn't realize that was a known issue (I only checked the list of open issues for elm-lang.org). Should I close this one, then?

**Comment by jvoigtlaender** [comment]
No problem.

Let's leave the decision about closing to @evancz.
