### ISSUE TITLE
clarify documentation of extensible record types?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-lang/elm-lang.org#529]
The sentences
> You can also define extensible records. This use has not come up much in practice so far, but it is pretty cool nonetheless.

in the section http://elm-lang.org/docs/records#record-types were found confusing. See this discussion: https://github.com/elm-lang/elm-compiler/issues/1283#issuecomment-182682422

**Comment by jvoigtlaender** [comment]
Also this: https://github.com/elm-lang/elm-lang.org/issues/514, where there was also confusion about whether or not adding and removing fields from record values is possible. (And the request that if not, that should be said explicitly in the documentation.)

**Comment by halfzebra** [comment]
I have updated the docs #555

**Comment by evancz** [comment]
Thanks @halfzebra

**Comment by Ziriax** [comment]
What about the opinion if this guy?

http://reasonablypolymorphic.com/blog/elm-is-wrong

Maybe nobody was using these extensible types since this feature does not exist in other mainstream languages (well actually Typescript allows extension of the "record" types, but not contraction as far as I know), and hence coders are unlikely to use this feature (it even does not exist in standard Haskell).

I found the paper about extensible types amazing, and thought it would be a  good fit for a language that transpiles to Javascript, since in that dynamic language fields are added and removed all the time.

Since unlike Purescript ELM does not have typeclasses, having real extensible types would be a good compromise IMHO.

**Comment by jvoigtlaender** [comment]
That guy is the guy who opened https://github.com/elm-lang/elm-compiler/issues/1283 (if I recall correctly).
