### ISSUE TITLE
Add CARFAX to the list of industry users?

### ISSUE THREAD

**Issue by cruhl** [elm-lang/elm-lang.org#632]
The DevOps team at CARFAX has rewritten several internal tools in Elm and is looking to expand our usage to the deploy/health dashboard (the largest internal app we have).

Is this enough to warrant a listing?
Thanks in advance!

**Comment by evancz** [comment]
Very cool! Can you point me to an SVG logo?

Also, are there any plans to blog about what's going on there?

**Comment by cruhl** [comment]
I'll see if I can dig up an SVG... I might post a write-up on Medium, but I'm not sure if that's quite alright just yet. Until then, I'm sure no one would be bothered if it was only an image. I'm really just hoping our brand can help soothe the nerves of potential adopters :)

**Comment by evancz** [comment]
I added it with just a link to the site. Let me know if there's ever something better to link to!

**Comment by cruhl** [comment]
What kind of article/write-up do you think would be most helpful or hasn't been covered before?

**Comment by evancz** [comment]
"We use it for X. Here's how we migrated. Here's what's different. Here are the tradeoffs." That kind of thing. Experience reports like this are useful because they spread information and let the community know they can look to you for guidance. Or like, here's some stuff we were working on that we thought was interesting for some reason.

Doing this kind of writing can also get folks interested in working with your team, so depending on your goals, this kind of writing can be pretty nice for everyone.

Hopefully that's somewhat helpful!
