### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by mxgrn** [elm-lang/elm-lang.org#637]
This line in the code: 
https://github.com/elm-lang/elm-lang.org/blob/master/src/pages/docs/syntax.elm#L238
seemingly results in a bad URL on the documentation page: `http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#>` (missing the second ">").

**Comment by evancz** [comment]
Does anyone know the fix? Is this something about the markdown parser that `>>` means something?

**Comment by evancz** [comment]
Does anyone know the fix? Is this something about the markdown parser that `>>` means something?

**Comment by evancz** [comment]
Can someone test? It is just using `elm-markdown`.

**Comment by OvermindDL1** [comment]
I happen to be using `elm-markdown` in my big project so let me test.
Yes, elm-markdown is broken, it is parsing it wrong and one of the `>` is vanishing.
However I did find a work-around after trying a few things.  Apparently elm-markdown does not support escaping inside urls (not sure if that is spec'd or not even), however putting three `>` did work, thus `[test](http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#>>>)` got turned into a string of 'test' with a link of `http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#>>`

So a hack-of-a-fix until elm-markdown is fixed is just to use three `http://package.elm-lang.org/packages/elm-lang/core/latest/Basics#>>>` with the three `>` at the end instead of just two, with maybe a note to fix it once elm-markdown is fixed.  :-)

**Comment by evancz** [comment]
Very weird, but that'll work! Do you mind doing a PR?

**Comment by OvermindDL1** [comment]
Done:  https://github.com/elm-lang/elm-lang.org/pull/641
