### ISSUE TITLE
Add Qualification to "no runtime exceptions" Claim

### ISSUE THREAD

**Issue by danny-andrews** [elm-lang/elm-lang.org#746]
The homepage states that Elm "Generate[s] JavaScript with great performance and no runtime exceptions." This, however, is a false claim. For example, the following code throws a runtime exception:
```js
f x = x
g y = y
b = f == g
```
https://github.com/elm-lang/elm-compiler/issues/1145

There should be an `*` with a note explaining this and any other edge-cases.

**Comment by danny-andrews** [comment]
https://github.com/elm-lang/core/issues/377

**Comment by evancz** [comment]
Right now the text about runtime exceptions is like this:

> # No Runtime Exceptions
>
> Unlike hand-written JavaScript, Elm code does not produce runtime exceptions in practice. Instead, Elm uses type inference to detect problems during compilation and give friendly hints. This way problems never make it to your users. NoRedInk has 80k+ lines of Elm, and after more than a year in production, it still has not produced a single runtime exception.

I think that constrains the claim and backs it up in a reasonable way.

Separately I am trying to imagine what the asterisk would say. Like "there are a handful of bugs that are so rare that in 2.5 years and 100k+ LOC, they have not appeared in practice, but now you know about bugs that we're working on fixing that you'll basically never see." It seems like such a small asterisk that the longform note about it seems to clarify enough.

I think it'd be helpful to know if other people who have tried out Elm feel the same way as you though. Perhaps I am not seeing it the same way, and a decent amount of people feel this is not correct.

**Comment by tdreyno** [comment]
For what it's worth, I got the modulo 0 runtime exception on my first day in Elm.

**Comment by nathanKramer** [comment]
Elm has an intentional runtime error: https://github.com/elm/core/issues/909

> For what it's worth, I got the modulo 0 runtime exception on my first day in Elm.

This, while anecdotal, opposes the claim that the asterisk should merely refer to "a handful of bugs that are so rare that in 2.5 years and 100k+ LOC, they have not appeared in practice",

Most notably: it isn't a bug (as far as I can tell from the issue)

IMHO it'd be nice to qualify the statement if the modulo case is not going to change.

I'd suggest this:

> No Runtime Exceptions
> Unlike hand-written JavaScript, Elm code does not produce runtime exceptions in practice*. Instead, Elm uses type inference to detect problems during compilation and give friendly hints. This way problems never make it to your users. NoRedInk has 80k+ lines of Elm, and after more than a year in production, it still has not produced a single runtime exception.
> *as long as you don't [mod by zero](https://github.com/elm/core/issues/377)!

The * has been placed in the paragraph, not the title, so that we don't kill the vibe right out of the gate. The disclaimer links to the potential runtime errors issue which I personally think is quite an impressive piece of evidence in favour of the claim.
If that's unappealing (and I expect it is, I don't really like the look of it), then I guess I'm curious, why is it not a bug? What accounts for the distance between it being a design choice, and being brushed under the carpet?
